CC = g++
CFLAG = -o

all: trabajadores_tareas_greedy trabajadores_tareas_greedy_tiempos trabajadores_tareas_greedy_por_pasos genera-trabajadores_tareas_en_el_main genera-trabajadores_tareas_funciones

trabajadores_tareas_greedy: 
	$(CC) trabajadores_tareas_greedy.cpp $(CFLAG) trabajadores_tareas_greedy

trabajadores_tareas_greedy_tiempos: 
	$(CC) trabajadores_tareas_greedy_tiempos.cpp $(CFLAG) trabajadores_tareas_greedy_tiempos

trabajadores_tareas_greedy_por_pasos: 
	$(CC) trabajadores_tareas_greedy_por_pasos.cpp $(CFLAG) trabajadores_tareas_greedy_por_pasos

genera-trabajadores_tareas_en_el_main:
	$(CC) genera-trabajadores_tareas_en_el_main.cpp $(CFLAG) genera-trabajadores_tareas_en_el_main

genera-trabajadores_tareas_funciones:
	$(CC) genera-trabajadores_tareas_funciones.cpp $(CFLAG) genera-trabajadores_tareas_funciones

clean:
	$(RM) trabajadores_tareas_greedy trabajadores_tareas_greedy_tiempos trabajadores_tareas_greedy_por_pasos genera-trabajadores_tareas_en_el_main genera-trabajadores_tareas_funciones





