CC = g++
CFLAG = -o

all: ITV ITV_tiempos ITV_generador

ITV:
	$(CC) -std=c++11 ITV.cpp $(CFLAG) ITV

ITV_tiempos:
	$(CC) -std=c++11 ITV_tiempos.cpp $(CFLAG) ITV_tiempos 

ITV_generador:
	$(CC) -std=c++11 ITV_generador.cpp $(CFLAG) ITV_generador

clean:
	$(RM) ITV ITV_tiempos ITV_generador





